### ISSUE TITLE
Familiarize with TomP2P

### ISSUE THREAD

**Issue by lroellin** [dwrtc/sa#3]
Make ourselves familiar with TomP2P

We discussed setting up a DHT between all clients. When a client goes online, it PUTs its current connection details with its ID as the key. When you want to reach this client, you could GET the connection details from the DHT and connect directly.

But, this is all very open for discussion!

**Comment by thde** [comment]
Building fails with Java 10. Some errors were fixed by updating "lombok" and adding sctp4nat as a dependency:

```java
    dependencies {
        implementation 'com.github.jonaswagner:sctp4nat:master'
        compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.2'
    }
```

**Comment by lroellin** [comment]
Apparently builds now with the latest commits!

**Comment by lroellin** [comment]
Set up just like in the lectures. Maybe also try to do it over computer boundaries

**Comment by lroellin** [comment]
We've done most of it during the DSA challenge project and in #19
