### ISSUE TITLE
Does WebRTC check latency to its STUN and Turn servers?

### ISSUE THREAD

**Issue by lroellin** [dwrtc/sa#37]
If we tell WebRTC what STUN and TURN servers it can use, does it automatically check the latency to those?
If not, how can we influence this decision? (e.g. a weighted list)

**Comment by lroellin** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/urls

"Avoid specifying an unnecessarily large number of URLs in the urls property; the startup time for your connection will go up substantially. Every server in the list will be contacted and tried out before one is selected to be used for negotiation."

**Comment by lroellin** [comment]
Seems like this is left to the implementation. Judging from https://serverfault.com/a/608440 

> ICE RFC doesn't specify what happens when multiple TURN servers are available:

Maybe we can find something official for Mozilla and Chrome/Chromium?

**Comment by thde** [comment]
https://www.twilio.com/docs/stun-turn/faq

**Comment by lroellin** [comment]
So it seems like this is just open to the implementation!

**Comment by lroellin** [comment]
https://stackoverflow.com/questions/53303156/how-to-influence-the-priority-of-turn-servers

**Comment by lroellin** [comment]
It is not defined how it does it. We can close this issue
