### ISSUE TITLE
Check requirements

### ISSUE THREAD

**Issue by lroellin** [dwrtc/sa#4]
Sort through the documents and check what we need to do

Keerthi mentioned that Thomas is already doing this, as part of what he requires from our side.

**Comment by lroellin** [comment]
Diese **Dokumentationselemente** müssen insbesondere die folgenden Angaben enthalten:
* Anforderungen spezifiziert:
  * Funktionale Anforderungen z.B. als Use Cases (short) oder User Stories beschrieben
  * Alle relevanten Nichtfunktionalen Anforderungen (NFA) und Qualitätsattribute abgedeckt und überprüfbar beschrieben

* Architektur und Design beschrieben:
* Mit begründeten Architekturentscheidungen
* Mit Diskussion, wie Qualitätsattribute sichergestellt wurden (welche Qualität
wurde erreicht?)
* Mit Dokumentation, welche Experimente/Tests durchgeführt wurden und
welche Lösungsoptionen aufgrund der Ergebnisse dieser Experimente/Tests
verworfen wurden (was ging schief?)
  * Installationsanleitung vorhanden (inklusive verwendete Entwicklungsumgebung und
Werkzeuge)
  * Test-Logs dokumentiert (bei Systemen mit User Interfaces: Dokumentation der
Usability Tests)

Dazu kommen die folgenden HSR-internen, nicht publizierte Dokumentationselemente (Abgabe nur für die Bewertung und Archivierung, in einer PDF-Datei):
* Formulare (z.B. Eigenständigkeitserklärung, Nutzungsrechte, ...)
* Persönliche Reflektion
* Projektplanung inkl. Risiko-Listen (Dokumentation der Versionen nach jeder Iteration)
* Zeitabrechnung nach sinnvollen Kategorien
* Sitzungsprotokolle

**Titelblatt**
Titelblatt gemäss Vorlage. Es steht eine deutsche und eine englische Version zur Verfügung.

**Aufgabenstellung**
Die vom Betreuer abgegebene und unterschriebene Aufgabenstellung (eingescannt).

**Comment by thde** [comment]
LGTM
